name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to release. E.g.: 0.0.1"
        required: true

jobs:
  release:
    name: "New release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      # This step will differ depending on your project setup
      # Fortunately, yarn has a built-in command for doing this!
      - name: Bump version in package.json
        run: npm version ${{ github.event.inputs.version }}

      - name: Merge release into main
        run: |
          git fetch --all
          git branch -a
          git pull origin main --allow-unrelated-histories
          git checkout main origin/main
          git merge -s theirs release/${{ github.event.inputs.version }}

      - name: Update develop branch
        run: |
          git checkout develop
          git merge -s theirs master
          npm version ${{ github.event.inputs.version }}-SNAPSHOT --git-tag-version false
          git push origin develop
