name: "Release"

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "The version you want to release. E.g.: 0.0.1"
        required: true
      nextDevelopmentVersion:
        description: "The next development version. E.g.: 0.0.1-SNAPSHOT"
        required: true

jobs:
  release:
    name: "New release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.releaseVersion }}

      - name: Bump version in package.json
        run: npm version ${{ github.event.inputs.releaseVersion }}

      - name: Preparing main branch
        run: |
          git fetch --all
          git branch -a
          git config pull.rebase true
          git checkout -b main origin/main
          git clean -fd
          git pull -u origin main --allow-unrelated-histories

      - name: Merge release into main
        run: |
          git merge release/${{ github.event.inputs.releaseVersion }}

      - name: Update develop branch
        run: |
          git checkout develop
          git clean -fd
          git merge master
          npm version ${{ github.event.inputs.nextDevelopmentVersion }} --git-tag-version false

      - name: Push changes
        run: |
          git push origin v${{ github.event.inputs.releaseVersion }}
          git push origin develop
          git push origin main
